sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WOTnJ21SVNXVXRw7Upyxu4z51pEWTy3yuDa6AJHJAoaCxDebkLLD55dHjmtqxxOVo5hSwVdWb3RcpNd/Y3deFYVae96HDomfU7aHPmTwdl5Tt87rHrDORSt1TP2inGTQUfty1NWwQLYwVj+3L4rtZpjG+vrqlxB4+YxfosAwfWgykrqzpOh4M7tiMVJgJJ4rLo/1XG2s3oXH3GMTjVbQ21XV6uwA1V/vZFSDKjm99fkuNZA0j9Cbecm5DNolL9bnLcwNy21oqEjwUe55S0/B5QAX+ngVTEBQKKjSMqhwX/9/fi2+iKqKxW6L2JvPWVT91/wws5KJPd4FwFPZdEulwdHvISLBMlutCHl4lDhTuc7W6sNDgHGtNFyIbO5svBHhM5Z0ctLUS37snV9wGOM48HPQWXz3ZQk4xkqEWfAuM+shlx0/DzV/V3r83IS2DLjKufDFtLBawlVDNAsOKreWjLz40mPqJTVNwXMNavIUhERgJQqJfFt69E69SBKG9fVNTjcYPW0UjlunWAeMagmS/wgG1q2wHfB7YmT7TXE/cEEI9uhvU7sIcosPyhDFcb2rTsYggHSKqQhIjnO6iUH04XzfWpFG/5yCBVaP1dQ/3o/Ro09jEAw2xVKqPA6/Gb2L/Zk9u406FgECWw5qvOEiD+IChjg2Tfx4EQYbV0xEoRQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Hamlet-Prince-of-Denmark_1524
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy